//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class Lift_Object: MonoBehaviour 
{
		/*public GameObject Crate;
		private Boolean Can_Lift = true;
		private GameObject new_cube;
	void Start()
	{
		//creates a new crate at the prefabs location
	new_cube = Instantiate (Crate, Crate.transform.position, Crate.transform.rotation)as GameObject;
	}

	void Update()
	{
	if (Can_Lift == true)
		{
		Vector3 Player_Pos = (transform.position);
		Player_Pos.y += 3;

		new_cube.transform.position = (Player_Pos);
		Debug.Log("Pos.y = "+new_cube.transform.position.y.ToString());
				
		}
				
	}

	void OnTriggerEnter(Collision target)
	{
		Debug.Log("Detected collisions");
		if (target.collider.name == "Crate") 
		{
			Can_Lift = true;
			
		}
		else Can_Lift = false;
	}
	*/
}
